### ISSUE TITLE
Leaving Barinade during fight breaks Barinade

### ISSUE THREAD

**Issue by Vsmit** [briaguya-ai/rando-issue-tracker#145] opened 2022-07-09 23:20 UTC
Don't have sword, ran out of sticks before the last hit, save and quit. Get sticks, come back, during the spawn cutscene, the Baris disappear when they attach to Barinade, then Barinade flys around the boss room while "still attached" to the ceiling, with a set of Baris spinning around it. Boomerang to stun, one hit with stick, Barinade dies, and now the cutscene is stopped.

https://user-images.githubusercontent.com/36902753/178125579-0c3ea0f4-2aed-4d4a-83f9-eec72c2637b2.mp4

**Comment by briaguya-ai** [comment] 2022-07-09 23:36
should probably look into all the boss fights and make sure save/reloading or dying/retrying works

**Comment by Flax4** [comment] 2022-07-09 23:47
Can repro by following the steps, then I messed around with debug mode and just checking it all out.

https://www.youtube.com/watch?v=t4m3_8cAV54

**Comment by leggettc18** [comment] 2022-07-10 17:46
Does rando do anything relating to skipping the intro cutscene here other than setting the flag for having watched the intro? Seems like some initialization steps are getting skipped here.

**Comment by Vsmit** [comment] 2022-07-10 18:28
If there are flags getting set, there's nothing relating to the intro cutscene. It shows every time you enter the room, with different effects dependent on how far into the fight you got, as per Flax's video.

**Comment by leggettc18** [comment] 2022-07-10 18:40
After leaving this comment, I went to go reproduce this in dev. The jenkins builds were crashing but there is a PR waiting to fix that. I was able to manually merge that in and get latest dev running. After that point I was able to reproduce this exact scenario in latest dev as well, so this is not rando specific. I'll go ahead and open an issue on the main SoH repo and link this one to it.

**Comment by briaguya-ai** [comment] 2022-07-10 19:31
closing this because it's not a rando specific thing

**Closed by briaguya-ai** 2022-07-10 19:31 UTC
Labels: definitely v1, bug
